const DMB_CONFIG = Object.freeze({
  APP_NAME: 'DMB ERP',
  VERSION: '1.0.4',
  TIMEZONE: 'America/Sao_Paulo',
  SESSION_SECONDS: 21600,
  MAX_UPLOAD_BYTES: 5 * 1024 * 1024,
  ROOT_FOLDER_NAME: 'DMB ERP',
  RECEIPTS_FOLDER_NAME: 'Comprovantes de Despesas',
  PROPERTIES: Object.freeze({
    SPREADSHEET_ID: 'DMB_SPREADSHEET_ID',
    ROOT_FOLDER_ID: 'DMB_ROOT_FOLDER_ID',
    RECEIPTS_FOLDER_ID: 'DMB_RECEIPTS_FOLDER_ID',
    PASSWORD_PEPPER: 'DMB_PASSWORD_PEPPER'
  }),
  SHEETS: Object.freeze({
    CONFIG: ['CHAVE', 'VALOR', 'DESCRICAO', 'ATUALIZADO_EM'],
    USUARIOS: ['ID', 'NOME', 'EMAIL', 'SENHA_HASH', 'SALT', 'PERFIL', 'VENDEDOR_ID', 'ATIVO', 'TROCAR_SENHA', 'CRIADO_EM', 'ATUALIZADO_EM'],
    VENDEDORES: ['ID', 'CODIGO_PROTHEUS', 'NOME', 'EMAIL', 'ROTA_PADRAO', 'SUPERVISOR_ID', 'GERENTE_ID', 'ATIVO', 'CRIADO_EM', 'ATUALIZADO_EM'],
    CLIENTES: ['ID', 'CODIGO_PROTHEUS', 'NOME', 'NOME_FANTASIA', 'VENDEDOR_ID', 'REGIAO_ID', 'SEGMENTO_ID', 'ESTADO', 'CIDADE', 'ATIVO', 'CRIADO_EM', 'ATUALIZADO_EM'],
    REGIOES: ['ID', 'CODIGO_PROTHEUS', 'NOME', 'ATIVO', 'CRIADO_EM', 'ATUALIZADO_EM'],
    SEGMENTOS: ['ID', 'CODIGO_PROTHEUS', 'NOME', 'ATIVO', 'CRIADO_EM', 'ATUALIZADO_EM'],
    FORNECEDORES: ['ID', 'CODIGO_PROTHEUS', 'NOME', 'CNPJ', 'EMAIL', 'TELEFONE', 'ATIVO', 'CRIADO_EM', 'ATUALIZADO_EM'],
    AGENDAMENTOS: ['ID', 'VENDEDOR_ID', 'CLIENTE_ID', 'DATA', 'ROTA', 'OBJETIVO', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
    VISITAS: ['ID', 'AGENDAMENTO_ID', 'VENDEDOR_ID', 'CLIENTE_ID', 'DATA', 'CONTATO', 'COMENTARIOS', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
    ADIANTAMENTOS: ['ID', 'VENDEDOR_ID', 'DATA', 'OBJETIVO', 'VALOR', 'PERIODO', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
    DESPESAS: ['ID', 'DATA', 'VENDEDOR_ID', 'VENDEDOR_NOME', 'ROTA', 'CLIENTE_ID', 'CLIENTE_NOME', 'CATEGORIA', 'DESCRICAO', 'VALOR', 'FORMA_PAGAMENTO', 'QUILOMETRAGEM', 'COMPROVANTE_URL', 'COMPROVANTE_ID', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
    PRESTACOES: ['ID', 'VENDEDOR_ID', 'PERIODO_INICIO', 'PERIODO_FIM', 'TOTAL_DESPESAS', 'TOTAL_ADIANTAMENTOS', 'SALDO', 'STATUS', 'CRIADO_EM', 'ATUALIZADO_EM'],
    APROVACOES: ['ID', 'TIPO', 'REFERENCIA_ID', 'APROVADOR_ID', 'DECISAO', 'COMENTARIO', 'DATA_HORA'],
    AUDITORIA: ['ID', 'DATA_HORA', 'USUARIO_ID', 'USUARIO_EMAIL', 'ACAO', 'MODULO', 'REFERENCIA_ID', 'DETALHES', 'DISPOSITIVO']
  })
});

function getConfigValue_(key, fallback) {
  const rows = getSheetObjects_('CONFIG');
  const item = rows.find(function(row) { return String(row.CHAVE) === String(key); });
  return item && item.VALOR !== '' ? item.VALOR : fallback;
}
