plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.dmb.tvcompras'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.dmb.tvcompras'
        minSdk 23
        targetSdk 35
        versionCode 17
        versionName '17.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
